
package Presentacion;


import java.awt.Color;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;






public class DashBoard extends javax.swing.JFrame {

     Color colEntered=new Color(153,153,153);
     Color colExited=new Color(34, 34, 34);
     frmLibro libro;
     frmPrestamo prestamo;
     frmCliente cliente;
     frmRevista revista;
     frmUsuario usuarios;
     
     
     int instanciaLibro=0;//Para controlar que se habra mas de un formulario a la vez
     int instanciaPrestamo=0;
     int instanciaCliente=0;
     int instanciaRevista=0;
     int instanciaUsuarios=0;
     
     
     
    public DashBoard() {
        initComponents(); 
        setIconImage(new ImageIcon(getClass().getResource("../Files/Books_30px_1.png")).getImage());//Icono del Formulario
        
        this.txtrolIdUser.setVisible(false);
        this.txtUserId.setVisible(false);
        //this.calendarLibros.setDate(Date.from(Instant.now()));
        this.setLocationRelativeTo(null);//con esta instruccion aparecera centrada la ventana 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPrestamos = new javax.swing.JLabel();
        btnLibros = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JLabel();
        btnClientes = new javax.swing.JLabel();
        btnReportes = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JLabel();
        btnRevistas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtnameUser = new javax.swing.JLabel();
        txtUserId = new javax.swing.JLabel();
        txtrolIdUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelLibros = new javax.swing.JPanel();
        jDesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DashBoard");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(34, 34, 34));

        jLabel1.setBackground(new java.awt.Color(202, 202, 202));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(202, 202, 202));
        jLabel1.setText("Library");

        btnPrestamos.setBackground(new java.awt.Color(34, 34, 34));
        btnPrestamos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPrestamos.setForeground(new java.awt.Color(202, 202, 202));
        btnPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Purchase Order_60px.png"))); // NOI18N
        btnPrestamos.setText("Prestamos");
        btnPrestamos.setOpaque(true);
        btnPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseExited(evt);
            }
        });

        btnLibros.setBackground(new java.awt.Color(34, 34, 34));
        btnLibros.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnLibros.setForeground(new java.awt.Color(202, 202, 202));
        btnLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Book Shelf_60px.png"))); // NOI18N
        btnLibros.setText("Libros");
        btnLibros.setToolTipText("");
        btnLibros.setOpaque(true);
        btnLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLibrosMouseClicked(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(34, 34, 34));
        btnUsuarios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(202, 202, 202));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Add User Group Man Man_60px.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setToolTipText("");
        btnUsuarios.setOpaque(true);
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(34, 34, 34));
        btnClientes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(202, 202, 202));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Queue_60px.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setOpaque(true);
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(34, 34, 34));
        btnReportes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(202, 202, 202));
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Area Chart_60px.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setToolTipText("");
        btnReportes.setOpaque(true);

        btnLogOut.setBackground(new java.awt.Color(34, 34, 34));
        btnLogOut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(202, 202, 202));
        btnLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Shutdown_60px.png"))); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setToolTipText("");
        btnLogOut.setOpaque(true);
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });

        btnRevistas.setBackground(new java.awt.Color(34, 34, 34));
        btnRevistas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRevistas.setForeground(new java.awt.Color(202, 202, 202));
        btnRevistas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRevistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Magazine_60px.png"))); // NOI18N
        btnRevistas.setText("Revistas");
        btnRevistas.setToolTipText("");
        btnRevistas.setOpaque(true);
        btnRevistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRevistasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
            .addComponent(btnLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRevistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRevistas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(34, 34, 34));

        txtnameUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtnameUser.setForeground(new java.awt.Color(202, 202, 202));

        txtUserId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtUserId.setForeground(new java.awt.Color(202, 202, 202));

        txtrolIdUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtrolIdUser.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(202, 202, 202));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/User_60px.png"))); // NOI18N
        jLabel2.setText("Usuario :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(641, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtrolIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnameUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtrolIdUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelLibros.setBackground(new java.awt.Color(255, 255, 255));
        panelLibros.setAutoscrolls(true);

        jDesktopPane.setAutoscrolls(true);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1169, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLibrosLayout = new javax.swing.GroupLayout(panelLibros);
        panelLibros.setLayout(panelLibrosLayout);
        panelLibrosLayout.setHorizontalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        panelLibrosLayout.setVerticalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseEntered
        btnPrestamos.setBackground(colEntered);
    }//GEN-LAST:event_btnPrestamosMouseEntered

    private void btnPrestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseExited
        btnPrestamos.setBackground(colExited);
    }//GEN-LAST:event_btnPrestamosMouseExited

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        System.exit(0);//Cierra la aplicacion
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosMouseClicked
 
        if(instanciaLibro<1){
            try {
                libro=new frmLibro();
                jDesktopPane.add(libro);
                libro.setMaximum(true);
                libro.show();
                instanciaLibro++;
            } catch (PropertyVetoException ex) {
                Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex);
            } 
        }  else{
            libro.dispose();
            instanciaLibro--;
            jDesktopPane.removeAll();
            
        }
    }//GEN-LAST:event_btnLibrosMouseClicked

    private void btnRevistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevistasMouseClicked
//            if(instanciaLibro<1){
//            try {
//                libro=new frmLibro();
//                jDesktopPane.add(libro);
//                libro.setMaximum(true);
//                libro.show();
//                instanciaLibro++;
//            } catch (PropertyVetoException ex) {
//                Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
//                JOptionPane.showMessageDialog(this, ex);
//            } 
//        }  else{
//            libro.dispose();
//            instanciaLibro--;
//            jDesktopPane.removeAll();
//            
//        }
    }//GEN-LAST:event_btnRevistasMouseClicked

    private void btnPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseClicked

        if(instanciaPrestamo<1)
        {
            try {
                prestamo=new frmPrestamo();
                jDesktopPane.add(prestamo);
                prestamo.setMaximum(true);
                prestamo.show();
                instanciaPrestamo++;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,ex);
            }
        }
        else{
         prestamo.dispose();
         instanciaPrestamo--;
         jDesktopPane.removeAll();
        }
    }//GEN-LAST:event_btnPrestamosMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
          if(instanciaCliente<1)
        {
            try {
                cliente=new frmCliente();
                jDesktopPane.add(cliente);
                cliente.setMaximum(true);
                cliente.show();
                instanciaCliente++;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,ex);
            }
        }
        else{
         cliente.dispose();
         instanciaCliente--;
         jDesktopPane.removeAll();
        }
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
      if(instanciaUsuarios<1){
            try {
                usuarios=new frmUsuario();
                jDesktopPane.add(usuarios);
                usuarios.setMaximum(true);
                usuarios.show();
                instanciaUsuarios++;
            } catch (PropertyVetoException ex) {
                Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex);
            } 
        }  else{
            usuarios.dispose();
            instanciaUsuarios--;
            jDesktopPane.removeAll();
            
        }
    }//GEN-LAST:event_btnUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClientes;
    private javax.swing.JLabel btnLibros;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JLabel btnPrestamos;
    private javax.swing.JLabel btnReportes;
    private javax.swing.JLabel btnRevistas;
    private javax.swing.JLabel btnUsuarios;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelLibros;
    public javax.swing.JLabel txtUserId;
    public javax.swing.JLabel txtnameUser;
    public javax.swing.JLabel txtrolIdUser;
    // End of variables declaration//GEN-END:variables

    
}
