
package Presentacion;

import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class frmPrestamo extends javax.swing.JInternalFrame {

    Date fecha;
    
    public frmPrestamo() {
        initComponents();
        
      Calendar calendar = Calendar.getInstance();
      calendar.setTime(fecha.from(Instant.now())); // Configuramos la fecha que se recibe	
      calendar.add(Calendar.DAY_OF_MONTH,5);  // numero de Dias a añadir, o restar en caso de Dias<0
	
      txtClienteIdPre.setVisible(false);
      txtClienteIdDev.setVisible(false);

      datePrestamo.setDate(fecha.from(Instant.now()));//establece la prestamo
      dateDevolucion.setDate(calendar.getTime());//establece la fecha de devolucion
 
    }
    
    /*Constructor cuando se insert un cliente*/
    public frmPrestamo(String Client,String ClientId){
        
        txtClientePre.setText(Client);
        txtClienteIdPre.setText(ClientId);
        txtClienteDev.setText(Client);
        txtClienteIdDev.setText(ClientId);
    }
    
    
    /*Constructor cuando se inserta libro o revista*/
    public frmPrestamo(Object[] DatosTabla)
    {
       
        DefaultTableModel modelo;

        String[] titulos = {"ID","Titulo","Categoria","Autor","Status"};

        Object[] registro = new Object[5];
        modelo = new DefaultTableModel(null, titulos);
        
        try {
        
        modelo.addRow(DatosTabla);
        
        jTablePrestamo.setModel(modelo);
         
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnClientePre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        datePrestamo = new com.toedter.calendar.JDateChooser();
        txtClientePre = new javax.swing.JTextField();
        dateDevolucion = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        btnLibro = new javax.swing.JButton();
        btnRevista = new javax.swing.JButton();
        brnRegistrarP = new javax.swing.JButton();
        txtClienteIdPre = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePrestamo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtClienteDev = new javax.swing.JTextField();
        btnClienteDev = new javax.swing.JButton();
        txtClienteIdDev = new javax.swing.JTextField();
        btnDevolver = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDevolucion = new javax.swing.JTable();

        setBorder(null);
        setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnClientePre.setBackground(new java.awt.Color(116, 178, 92));
        btnClientePre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClientePre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/User_30px_1.png"))); // NOI18N
        btnClientePre.setText("Cliente");
        btnClientePre.setContentAreaFilled(false);
        btnClientePre.setOpaque(true);
        btnClientePre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientePreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fecha Prestamo");

        txtClientePre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Fecha Devolucion");

        btnLibro.setBackground(new java.awt.Color(116, 178, 92));
        btnLibro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Books_30px_1.png"))); // NOI18N
        btnLibro.setText("Libro");
        btnLibro.setContentAreaFilled(false);
        btnLibro.setOpaque(true);
        btnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroActionPerformed(evt);
            }
        });

        btnRevista.setBackground(new java.awt.Color(116, 178, 92));
        btnRevista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRevista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Revista_30px.png"))); // NOI18N
        btnRevista.setText("Revista");
        btnRevista.setContentAreaFilled(false);
        btnRevista.setOpaque(true);

        brnRegistrarP.setBackground(new java.awt.Color(0, 179, 143));
        brnRegistrarP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brnRegistrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Save_30px.png"))); // NOI18N
        brnRegistrarP.setText("Registrar Prestamo");
        brnRegistrarP.setContentAreaFilled(false);
        brnRegistrarP.setOpaque(true);

        jTablePrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TITULO", "AUTOR", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablePrestamo);
        if (jTablePrestamo.getColumnModel().getColumnCount() > 0) {
            jTablePrestamo.getColumnModel().getColumn(0).setHeaderValue("ID");
            jTablePrestamo.getColumnModel().getColumn(1).setHeaderValue("TITULO");
            jTablePrestamo.getColumnModel().getColumn(2).setHeaderValue("AUTOR");
            jTablePrestamo.getColumnModel().getColumn(3).setHeaderValue("TIPO");
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnClientePre)
                        .addGap(18, 18, 18)
                        .addComponent(txtClientePre))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(datePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClienteIdPre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRevista)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(brnRegistrarP)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClientePre)
                        .addComponent(txtClientePre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtClienteIdPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLibro)
                        .addComponent(btnRevista, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(brnRegistrarP)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Prestamos", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtClienteDev.setEditable(false);
        txtClienteDev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnClienteDev.setBackground(new java.awt.Color(116, 178, 92));
        btnClienteDev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClienteDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/User_30px_1.png"))); // NOI18N
        btnClienteDev.setText("Cliente");
        btnClienteDev.setContentAreaFilled(false);
        btnClienteDev.setOpaque(true);

        btnDevolver.setBackground(new java.awt.Color(0, 179, 143));
        btnDevolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Refresh_30px.png"))); // NOI18N
        btnDevolver.setText("Devolver");
        btnDevolver.setContentAreaFilled(false);
        btnDevolver.setOpaque(true);

        jTableDevolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "TITULO", "AUTOR", "TIPO"
            }
        ));
        jScrollPane4.setViewportView(jTableDevolucion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnClienteDev)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDevolver)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtClienteDev, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClienteIdDev, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteDev, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienteDev)
                    .addComponent(txtClienteIdDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnDevolver)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Devoluciones", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientePreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientePreActionPerformed
        DialogClientePrestamo cliente=new DialogClientePrestamo(null, true);
        
        cliente.setVisible(true);
        
        
    }//GEN-LAST:event_btnClientePreActionPerformed

    private void btnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroActionPerformed
        DialogLibroPrestamo libro=new DialogLibroPrestamo(null, true);
        
        libro.setVisible(true);
    }//GEN-LAST:event_btnLibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnRegistrarP;
    private javax.swing.JButton btnClienteDev;
    private javax.swing.JButton btnClientePre;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnLibro;
    private javax.swing.JButton btnRevista;
    private com.toedter.calendar.JDateChooser dateDevolucion;
    private com.toedter.calendar.JDateChooser datePrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDevolucion;
    public javax.swing.JTable jTablePrestamo;
    private javax.swing.JTextField txtClienteDev;
    private javax.swing.JTextField txtClienteIdDev;
    public static javax.swing.JTextField txtClienteIdPre;
    public static javax.swing.JTextField txtClientePre;
    // End of variables declaration//GEN-END:variables
}
