
package Presentacion;

import Datos.DPrestamo;
import Negocio.NLibro;
import Negocio.NPrestamo;
import Negocio.NRevista;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class frmPrestamo extends javax.swing.JInternalFrame {

    Date fecha;
  
    public frmPrestamo() {
        initComponents();
   
      Calendar calendar = Calendar.getInstance();
      calendar.setTime(fecha.from(Instant.now())); // Configuramos la fecha que se recibe	
      calendar.add(Calendar.DAY_OF_MONTH,5);  // numero de Dias a añadir, o restar en caso de Dias<0
	
      txtClienteIdPre.setVisible(false);
      txtClienteIdDev.setVisible(false);

      datePrestamo.setDate(fecha.from(Instant.now()));//establece la prestamo
      dateDevolucion.setDate(calendar.getTime());//establece la fecha de devolucion
 
        llenar_TablaLibro("Where Status='Disponible'");
        llenar_TablaRevista("Where Status='Disponible'");
    }
    
    /*Constructor cuando se insert un cliente*/
    public frmPrestamo(String Client,String ClientId){
        
        txtClientePre.setText(Client);
        txtClienteIdPre.setText(ClientId);
        txtClienteDev.setText(Client);
        txtClienteIdDev.setText(ClientId);

    }
    
    /*Constructor cuando se inserta libro o revista*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnClientePre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtClientePre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        brnRegistrarP = new javax.swing.JButton();
        txtClienteIdPre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLibro = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRevista = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTablePrestamo = new javax.swing.JTable();
        btnAgregarLibro = new javax.swing.JButton();
        btnAgregarRevista = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        datePrestamo = new com.toedter.calendar.JDateChooser();
        dateDevolucion = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        txtClienteDev = new javax.swing.JTextField();
        btnClienteDev = new javax.swing.JButton();
        txtClienteIdDev = new javax.swing.JTextField();
        btnDevolver = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDevolucion = new javax.swing.JTable();

        setBorder(null);
        setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnClientePre.setBackground(new java.awt.Color(116, 178, 92));
        btnClientePre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClientePre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/User_30px_1.png"))); // NOI18N
        btnClientePre.setText("Cliente");
        btnClientePre.setContentAreaFilled(false);
        btnClientePre.setOpaque(true);
        btnClientePre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientePreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fecha Prestamo");

        txtClientePre.setEditable(false);
        txtClientePre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Fecha Devolucion");

        brnRegistrarP.setBackground(new java.awt.Color(0, 179, 143));
        brnRegistrarP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brnRegistrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Save_30px.png"))); // NOI18N
        brnRegistrarP.setText("Registrar Prestamo");
        brnRegistrarP.setContentAreaFilled(false);
        brnRegistrarP.setOpaque(true);
        brnRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRegistrarPActionPerformed(evt);
            }
        });

        jTableLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableLibro);

        jTableRevista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableRevista);

        jTablePrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Autor", "Tipo"
            }
        ));
        jScrollPane5.setViewportView(jTablePrestamo);

        btnAgregarLibro.setText("Agregar Libro");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        btnAgregarRevista.setText("Agregar revista");
        btnAgregarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRevistaActionPerformed(evt);
            }
        });

        jButton1.setText("Borrar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnAgregarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarRevista)
                .addGap(246, 246, 246))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnClientePre)
                                .addGap(18, 18, 18)
                                .addComponent(txtClientePre, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClienteIdPre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(datePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(brnRegistrarP))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jButton1)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientePre)
                    .addComponent(txtClientePre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClienteIdPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addComponent(datePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(dateDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarRevista)
                    .addComponent(btnAgregarLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brnRegistrarP)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Prestamos", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtClienteDev.setEditable(false);
        txtClienteDev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnClienteDev.setBackground(new java.awt.Color(116, 178, 92));
        btnClienteDev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClienteDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/User_30px_1.png"))); // NOI18N
        btnClienteDev.setText("Cliente");
        btnClienteDev.setContentAreaFilled(false);
        btnClienteDev.setOpaque(true);
        btnClienteDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteDevActionPerformed(evt);
            }
        });

        btnDevolver.setBackground(new java.awt.Color(0, 179, 143));
        btnDevolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Refresh_30px.png"))); // NOI18N
        btnDevolver.setText("Devolver");
        btnDevolver.setContentAreaFilled(false);
        btnDevolver.setOpaque(true);

        jTableDevolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha_Prestamo", "Fecha_Devolucion", "LibroId_RevistaId", "Tipo"
            }
        ));
        jScrollPane4.setViewportView(jTableDevolucion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnClienteDev)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDevolver)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtClienteDev, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClienteIdDev, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteDev, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienteDev)
                    .addComponent(txtClienteIdDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(btnDevolver)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Devoluciones", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientePreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientePreActionPerformed
        
        DialogClientePrestamo cliente=new DialogClientePrestamo(null,true);
        
        cliente.setVisible(true);
        
        
    }//GEN-LAST:event_btnClientePreActionPerformed

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        
      if(jTablePrestamo.getRowCount()<3){
          if(jTableLibro.getSelectedRow()>=0){
          DefaultTableModel model=(DefaultTableModel) jTablePrestamo.getModel();
           String[] data=new String[4];
           
           data[0]=String.valueOf(jTableLibro.getValueAt(jTableLibro.getSelectedRow(),0));
           data[1]=String.valueOf(jTableLibro.getValueAt(jTableLibro.getSelectedRow(),1));
           data[2]=String.valueOf(jTableLibro.getValueAt(jTableLibro.getSelectedRow(),3));
           data[3]="Libro";
           
           boolean existe=false;
              for (int i = 0; i < jTablePrestamo.getRowCount(); i++) {
                  
                   if(jTablePrestamo.getValueAt(i,1).equals(data[1]))
                   {existe=true;}
              }
           
              if(existe==false)
              {
           model.addRow(data);
              }
          }
      }
        
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void btnAgregarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRevistaActionPerformed
         
        if(jTablePrestamo.getRowCount()<3){
            if(jTableRevista.getSelectedRow()>=0){
        DefaultTableModel model=(DefaultTableModel) jTablePrestamo.getModel();
           String[] data=new String[4];
           
           data[0]=String.valueOf(jTableRevista.getValueAt(jTableRevista.getSelectedRow(),0));
           data[1]=String.valueOf(jTableRevista.getValueAt(jTableRevista.getSelectedRow(),1));
           data[2]="";//String.valueOf(jTableRevista.getValueAt(jTableRevista.getSelectedRow(),3));
           data[3]="Revista";
           
           boolean existe=false;
              for (int i = 0; i < jTablePrestamo.getRowCount(); i++) {
                  
                   if(jTablePrestamo.getValueAt(i,1).equals(data[1]))
                   {existe=true;}
              }
           
              if(existe==false)
              {
           model.addRow(data);
              }
              
            }
        }
    }//GEN-LAST:event_btnAgregarRevistaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model=(DefaultTableModel) jTablePrestamo.getModel();
        if(jTablePrestamo.getRowCount()>0)
        {
            if(jTablePrestamo.getSelectedRow()>=0){
         model.removeRow(jTablePrestamo.getSelectedRow());
            }
            else{ JOptionPane.showMessageDialog(null, "Seleccione un Prestamo para Borrar");}
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void brnRegistrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRegistrarPActionPerformed
        String cadenaId="";
        String cadenaTipo="";
        
        if(!txtClientePre.getText().equals("") && jTablePrestamo.getRowCount()>0)
        {
        NPrestamo prestamotools=new NPrestamo();
        DPrestamo prestamo=new DPrestamo();
     
        prestamo.setClienteId(Integer.parseInt(txtClienteIdPre.getText()));
        prestamo.setUserId(1);
        
        //==================Cambiar formato de Fecha para capturar
        String formato = datePrestamo.getDateFormatString();
        Date date = datePrestamo.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        
        String forma = dateDevolucion.getDateFormatString();
        Date dat = dateDevolucion.getDate();
        SimpleDateFormat sdfa = new SimpleDateFormat(forma);
        //=====================================
        
        prestamo.setFechaPrestamo(String.valueOf(sdf.format(date)));
        prestamo.setFechaDevolucion(String.valueOf(sdfa.format(dat)));
        
            for (int i = 0; i < jTablePrestamo.getRowCount(); i++) {
                
            cadenaId=cadenaId+jTablePrestamo.getValueAt(i,0).toString()+"$";
            cadenaTipo=cadenaTipo+jTablePrestamo.getValueAt(i,3).toString()+"$";
            }
        prestamo.setLibroId_RevistaId(cadenaId);
        prestamo.setTipo(cadenaTipo);
            
          boolean result= prestamotools.GuardarPrestamo(prestamo,jTablePrestamo.getRowCount());
          
          if(result)
          {
           JOptionPane.showMessageDialog(null, "Se Guardo correctamente \nel prestamo");
           this.dispose();
          }
        }
        else
        {
         JOptionPane.showMessageDialog(null, "Ingrege Cliente y Libros");
        }
        
        
    }//GEN-LAST:event_brnRegistrarPActionPerformed

    private void btnClienteDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteDevActionPerformed
        DialogClientePrestamo cliente=new DialogClientePrestamo(null,true);
        
        cliente.setVisible(true);             
    }//GEN-LAST:event_btnClienteDevActionPerformed

      private  void llenar_TablaLibro(String filtro) {
        try {
            DefaultTableModel modelo;
            NLibro libro = new NLibro();
            modelo =libro.fillDataTable(filtro);
            
            jTableLibro.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
  }
      
           private  void llenar_TablaRevista(String filtro) {
        try {
            DefaultTableModel modelo;
            NRevista libro = new NRevista();
            modelo =libro.fillDataTable(filtro);
            
            jTableRevista.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
  }
      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnRegistrarP;
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnAgregarRevista;
    private javax.swing.JButton btnClienteDev;
    private javax.swing.JButton btnClientePre;
    private javax.swing.JButton btnDevolver;
    private com.toedter.calendar.JDateChooser dateDevolucion;
    private com.toedter.calendar.JDateChooser datePrestamo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDevolucion;
    private javax.swing.JTable jTableLibro;
    private javax.swing.JTable jTablePrestamo;
    private javax.swing.JTable jTableRevista;
    private javax.swing.JTextField txtClienteDev;
    private javax.swing.JTextField txtClienteIdDev;
    public static javax.swing.JTextField txtClienteIdPre;
    public static javax.swing.JTextField txtClientePre;
    // End of variables declaration//GEN-END:variables
}
