/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DUsuarios;
import Negocio.NUsuarios;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Workgroup
 */
public class frmUsuario extends javax.swing.JInternalFrame {

 NUsuarios libroTools;
    
    public frmUsuario() {
        initComponents();
       
        libroTools=new NUsuarios();
        
        apply_filters();
        
        this.btnModificar.setEnabled(false);
        
        this.btnGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelConsulta1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        txtGetNombre1 = new javax.swing.JTextField();
        txtGetApellido1 = new javax.swing.JTextField();
        btnTema = new javax.swing.JButton();
        btnTitulo = new javax.swing.JButton();
        panelMantenimiento1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        txtUsuNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtUsuApellido = new javax.swing.JTextField();
        txtUsuContraseña = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        panelConsulta1.setBackground(new java.awt.Color(255, 255, 255));
        panelConsulta1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Usuario", "Contraseña", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableUsuarioMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUsuario);

        txtGetNombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtGetApellido1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnTema.setBackground(new java.awt.Color(54, 177, 124));
        btnTema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Search_30px.png"))); // NOI18N
        btnTema.setText("Apellido");
        btnTema.setContentAreaFilled(false);
        btnTema.setOpaque(true);
        btnTema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTemaMouseClicked(evt);
            }
        });

        btnTitulo.setBackground(new java.awt.Color(54, 177, 124));
        btnTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Search_30px.png"))); // NOI18N
        btnTitulo.setText("Nombre");
        btnTitulo.setContentAreaFilled(false);
        btnTitulo.setOpaque(true);
        btnTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTituloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelConsulta1Layout = new javax.swing.GroupLayout(panelConsulta1);
        panelConsulta1.setLayout(panelConsulta1Layout);
        panelConsulta1Layout.setHorizontalGroup(
            panelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsulta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addGroup(panelConsulta1Layout.createSequentialGroup()
                        .addComponent(txtGetNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTitulo)
                        .addGap(192, 192, 192)
                        .addComponent(txtGetApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnTema)))
                .addContainerGap())
        );
        panelConsulta1Layout.setVerticalGroup(
            panelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsulta1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(panelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTema, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGetApellido1))
                    .addGroup(panelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGetNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Consulta", panelConsulta1);

        panelMantenimiento1.setBackground(new java.awt.Color(255, 255, 255));
        panelMantenimiento1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mantenimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("UsuarioId");

        txtUserId.setEditable(false);
        txtUserId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtUsuNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Nombre");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Contraseña");

        btnNuevo.setBackground(new java.awt.Color(54, 177, 124));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Add File_30px.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setOpaque(true);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(54, 177, 124));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Refresh_30px.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setContentAreaFilled(false);
        btnModificar.setOpaque(true);
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(54, 177, 124));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Save_30px.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Apellido");

        txtUsuApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtUsuContraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Usuario");

        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelMantenimiento1Layout = new javax.swing.GroupLayout(panelMantenimiento1);
        panelMantenimiento1.setLayout(panelMantenimiento1Layout);
        panelMantenimiento1Layout.setHorizontalGroup(
            panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantenimiento1Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addGroup(panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantenimiento1Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(42, 42, 42)
                        .addComponent(btnModificar)
                        .addGap(32, 32, 32)
                        .addComponent(btnGuardar))
                    .addGroup(panelMantenimiento1Layout.createSequentialGroup()
                        .addGroup(panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMantenimiento1Layout.createSequentialGroup()
                                .addGroup(panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9))
                                .addGap(122, 122, 122)
                                .addGroup(panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsuContraseña)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtUsuNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUsuApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(412, 412, 412))
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addContainerGap())
        );
        panelMantenimiento1Layout.setVerticalGroup(
            panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantenimiento1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUsuNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtUsuApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtUsuContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelMantenimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Mantenimiento", panelMantenimiento1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMousePressed

        if(evt.getClickCount()==2)
        {
            JTable table =(JTable) evt.getSource();

            this.txtUserId.setText(String.valueOf(table.getValueAt(table.getSelectedRow(),0)));
            this.txtUsuNombre.setText(String.valueOf(table.getValueAt(table.getSelectedRow(),1)));
            this.txtUsuApellido.setText(String.valueOf(table.getValueAt(table.getSelectedRow(),2)));
            this.txtUsuario.setText(String.valueOf(table.getValueAt(table.getSelectedRow(),3)));
            this.txtUsuContraseña.setText(String.valueOf(table.getValueAt(table.getSelectedRow(),4)));

            jTabbedPane2.setSelectedIndex(1);

            this.btnModificar.setEnabled(true);
        }
    }//GEN-LAST:event_jTableUsuarioMousePressed

    private void btnTemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTemaMouseClicked
        apply_filters();
    }//GEN-LAST:event_btnTemaMouseClicked

    private void btnTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTituloMouseClicked
        apply_filters();
    }//GEN-LAST:event_btnTituloMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        this.btnModificar.setEnabled(false);
        this.btnGuardar.setEnabled(true);

        //Limpiar los campos
        this.txtUserId.setText("");
        this.txtUsuNombre.setText("");
        this.txtUsuApellido.setText("");
        this.txtUsuContraseña.setText("");

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked

    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:

        if(!txtUsuNombre.getText().equals("") && !txtUsuApellido.getText().equals("") && !txtUsuario.getText().equals("") && !txtUsuContraseña.getText().equals(""))
        {
            DUsuarios obj=new DUsuarios();

            obj.setUserId(Integer.parseInt(txtUserId.getText()));
            obj.setNombre(txtUsuNombre.getText());
            obj.setApellido(txtUsuApellido.getText());
            obj.setLogin(txtUsuario.getText());
            obj.setPassword(txtUsuContraseña.getText());

            boolean result= libroTools.actualizar(obj);

            if(result)
            {
                JOptionPane.showMessageDialog(null,"Se actualizo correctamente");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"No se pudo Actualizar");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Faltan Datos");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        DUsuarios obj=new DUsuarios();

        obj.setUserId(Integer.parseInt(txtUserId.getText()));
        obj.setNombre(txtUsuNombre.getText());
        obj.setApellido(txtUsuApellido.getText());
        obj.setLogin(txtUsuario.getText());
        obj.setPassword(txtUsuContraseña.getText());

        boolean isExiste=libroTools.VerificaUser(obj);

        if(isExiste)
        {
            JOptionPane.showMessageDialog(null,"Ya Existe el Usuario en la Base de Datos");
        }
        else
        {
            boolean result= libroTools.insertar(obj);

            if(result)
            {
                JOptionPane.showMessageDialog(null, "Se inserto el Registro Correctamente");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se logro ingresar el Registro");
            }

        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        //Limpiar los campos
        this.txtUserId.setText("");
        this.txtUsuNombre.setText("");
        this.txtUsuApellido.setText("");
        this.txtUsuContraseña.setText("");

        this.btnModificar.setEnabled(false);

        this.btnGuardar.setEnabled(false);

        if(jTabbedPane2.getSelectedIndex()==1)
        {
            apply_filters();
        }
    }//GEN-LAST:event_jTabbedPane2MouseClicked
private void apply_filters(){
    {
    int x=0;
    String query="";
    if(!txtGetNombre1.getText().equals(""))
    {
        if(x==0)
        {
         query="WHERE ";
         x++;
        }
        else
        {
         query="AND ";
        }
        query=query+"cli.Nombre like '"+txtGetNombre1.getText()+"%' ";
    }
    
    if(!txtGetApellido1.getText().equals(""))
    {
      if(x==0)
      {
       query="WHERE ";
       x++;
      }
      else
      {
          query="AND ";
      }
      query=query+"cli.Apellido like '"+txtGetApellido1.getText()+"%' ";
    }
        llenar_Tabla(query);
    }
}
  
    
  private  void llenar_Tabla(String filtro) {
        try {
            DefaultTableModel modelo;
            NUsuarios Usuario = new NUsuarios();
            modelo= Usuario.fillDataTable(filtro);
            
            jTableUsuario.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnTema;
    private javax.swing.JButton btnTitulo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JPanel panelConsulta1;
    private javax.swing.JPanel panelMantenimiento1;
    private javax.swing.JTextField txtGetApellido1;
    private javax.swing.JTextField txtGetNombre1;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUsuApellido;
    private javax.swing.JTextField txtUsuContraseña;
    private javax.swing.JTextField txtUsuNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
